### ISSUE TITLE
Worker queue

### ISSUE THREAD

**Issue by amirhnajafiz** [1995parham/koi#1]
@1995parham @mehditeymorian, I see that you created a QueueSize field in Worker, but you never used it anywhere.

```go
type Worker[T any, E any] struct {
	QueueSize       int
	ConcurrentCount int64
	Work            func(T) *E
}
```

I want to know what is the usage of this queue?
Is it like **cpu processing queue**?

**Comment by amirhnajafiz** [comment]
I have this idea of creating a **queue list** for each worker, then each time a new request comes we select the worker with less processes in its queue list and give that request to selected worker. 
And for finding the worker with minimum processes in its list we can use **min-heap.**

**Comment by 1995parham** [comment]
I love the idea @amirhnajafiz jan. I think we will have high load on our min-heap when tasks are coming and going very fast. if it can handle this load, I think we will be good.

**Comment by amirhnajafiz** [comment]
@1995parham jan, I implemented a heap library in Golang. [Github repo](https://github.com/amirhnajafiz/pyramid)

I tested the module with a load of 1 Million updates on 10 thousand data items and the response time was less than 12 seconds. 
I think we can use this heap module inside of our pond to manage workers.

**Comment by 1995parham** [comment]
@amirhnajafiz great. We can use it :raised_hands:
